Parameters:
  Country:
    Type: String
    Default: es
    AllowedValues:
      - es
      - de
      - pt
      - nl
      - ar
      - mc
      - mx
      - us
    Description: Name of the country for the tag
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - qa
      - stg
      - pre
      - ocu
      - sha
      - prod
    Description: Name of the environment for the tag
  Project:
    Type: String
    Default: test
    Description: Name of the project for the tag
  AthenaDataSourceWorkgroup01:
    Type: String
    Default: primary
    Description: The Athena workgroup quicksight uses to connect by datasource
  AthenaDatabaseName:
    Type: String
    Default: santander
    Description: Athena Database Name used for QS dataset queries
  AthenaDataSourceName:
    Type: String
    Description: Athena Datasource from quicksight
  AthenaDataSourceArn:
    Type: String
    Description: Athena DataSource Arn
  AthenaDataSourceId:
    Type: String
    Description: Athena DataSource ID
  PrincipalArn:
    Type: String
    Description: Permissions Principal ARN
  QuickSightDashboardName:
    Type: String
    Description: Name for quicksight dashboard
  QuickSightDashboardId:
    Type: String
    Description: Custom id for QuickSight Dashboard
  QuickSightDashboardSheetId01:
    Type: String
    Description: Custom sheet id for QuickSight Dashboard
  QuickSightDashboardSheetId02:
    Type: String
    Description: Custom sheet id for QuickSight Dashboard
  QuickSightDataSetId:
    Type: String
    Description: Custom id for QuickSight DataSet
  QuickSightUsername:
    Type: String
    Default: master
    Description: Quicksight username
  QuickSightPrincipalType:
    Type: String
    Default: user
    Description: Is the type of user that has permissions to use the datas source usually is a user type or group
  QuickSightNamespace:
    Type: String
    Default: default
    Description: Name of the namespace this principal has access to
  QuickSightDashboardDataSetARN01:
    Type: String
    Description: ARN for QuickSight DataSet
  QuickSightDashboardDataSetName01:
    Type: String
    Description: Name for QuickSight DataSet
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
Resources:
  dashboard02:
    Type: AWS::QuickSight::Dashboard
    Properties:
      AwsAccountId:
        Ref: AWS::AccountId
      DashboardId:
        Ref: QuickSightDashboardId
      Definition:
        AnalysisDefaults:
          DefaultNewSheetConfiguration:
            InteractiveLayoutConfiguration:
              Grid:
                CanvasSizeOptions:
                  ScreenCanvasSizeOptions:
                    OptimizedViewPortWidth: 1600px
                    ResizeOption: FIXED
            SheetContentType: INTERACTIVE
        CalculatedFields: []
        DataSetIdentifierDeclarations:
          - DataSetArn:
              Ref: QuickSightDashboardDataSetARN01
            Identifier:
              Ref: QuickSightDashboardDataSetName01
        FilterGroups: []
        ParameterDeclarations: []
        Sheets:
          - ContentType: INTERACTIVE
            Layouts:
              - Configuration:
                  GridLayout:
                    Elements:
                      - ColumnIndex: 0
                        ColumnSpan: 20
                        ElementId: e6390395-4a03-4d80-b862-a4d3506173c7_cec271a3-0eb5-404b-970b-c8fb60256cc1
                        ElementType: VISUAL
                        RowIndex: 0
                        RowSpan: 6
                      - ColumnSpan: 18
                        ElementId: e6390395-4a03-4d80-b862-a4d3506173c7_326755c4-51cd-4e7b-85ce-e7f06bb8ea8e
                        ElementType: VISUAL
                        RowSpan: 12
            Name: Sheet 1
            SheetId:
              Ref: QuickSightDashboardSheetId01
            Visuals:
              - LineChartVisual:
                  Actions: []
                  ChartConfiguration:
                    DataLabels:
                      Overlap: DISABLE_OVERLAP
                      Visibility: HIDDEN
                    FieldWells:
                      LineChartAggregatedFieldWells:
                        Category:
                          - DateDimensionField:
                              Column:
                                ColumnName: Date
                                DataSetIdentifier: dashboard02
                              FieldId: ColumnId-1.0.1703687945115
                              HierarchyId: ColumnId-1.0.1703687945115
                        Colors: []
                        Values: []
                    SortConfiguration:
                      CategoryItemsLimitConfiguration:
                        OtherCategories: INCLUDE
                      ColorItemsLimitConfiguration:
                        OtherCategories: INCLUDE
                      SmallMultiplesLimitConfiguration:
                        OtherCategories: INCLUDE
                    Tooltip:
                      FieldBasedTooltip:
                        AggregationVisibility: HIDDEN
                        TooltipFields:
                          - FieldTooltipItem:
                              FieldId: ColumnId-1.0.1703687945115
                              Visibility: VISIBLE
                        TooltipTitleType: PRIMARY_VALUE
                      SelectedTooltipType: DETAILED
                      TooltipVisibility: VISIBLE
                    Type: LINE
                  ColumnHierarchies:
                    - DateTimeHierarchy:
                        DrillDownFilters: []
                        HierarchyId: ColumnId-1.0.1703687945115
                  Subtitle:
                    Visibility: VISIBLE
                  Title:
                    Visibility: VISIBLE
                  VisualId: ce7svZarSaXIuCDKA7gh1gdWukhwNsnF6b787nwV9WfVoB2npubgTltgMoYivu1u
              - PieChartVisual:
                  Actions: []
                  ChartConfiguration:
                    DataLabels:
                      Overlap: DISABLE_OVERLAP
                      Visibility: VISIBLE
                    DonutOptions:
                      ArcOptions:
                        ArcThickness: WHOLE
                    FieldWells:
                      PieChartAggregatedFieldWells:
                        Category:
                          - CategoricalDimensionField:
                              Column:
                                ColumnName: Region
                                DataSetIdentifier: dashboard02
                              FieldId: ColumnId-10.0.1703688413615
                        Values: []
                    SortConfiguration:
                      CategoryItemsLimit:
                        OtherCategories: INCLUDE
                      SmallMultiplesLimitConfiguration:
                        OtherCategories: INCLUDE
                    Tooltip:
                      FieldBasedTooltip:
                        AggregationVisibility: HIDDEN
                        TooltipFields:
                          - FieldTooltipItem:
                              FieldId: ColumnId-10.0.1703688413615
                              Visibility: VISIBLE
                        TooltipTitleType: PRIMARY_VALUE
                      SelectedTooltipType: DETAILED
                      TooltipVisibility: VISIBLE
                  ColumnHierarchies: []
                  Subtitle:
                    Visibility: VISIBLE
                  Title:
                    Visibility: VISIBLE
                  VisualId: dwLn2QipbUtCEZmnq86lF7bBBGi8cxWgJuN539d0XdHXgIR0jghgC0W9vPrvxrIy
          - ContentType: INTERACTIVE
            Layouts:
              - Configuration:
                  GridLayout:
                    CanvasSizeOptions:
                      ScreenCanvasSizeOptions:
                        OptimizedViewPortWidth: 1600px
                        ResizeOption: FIXED
                    Elements:
                      - ColumnSpan: 18
                        ElementId: e6390395-4a03-4d80-b862-a4d3506173c7_6e9ac621-a804-4aea-b858-ea0c1c19e300
                        ElementType: VISUAL
                        RowSpan: 12
            Name: Sheet 3
            SheetId:
              Ref: QuickSightDashboardSheetId02
            Visuals:
              - LineChartVisual:
                  Actions: []
                  ChartConfiguration:
                    DataLabels:
                      Overlap: DISABLE_OVERLAP
                      Visibility: HIDDEN
                    FieldWells:
                      LineChartAggregatedFieldWells:
                        Category:
                          - CategoricalDimensionField:
                              Column:
                                ColumnName: Region
                                DataSetIdentifier: dashboard02
                              FieldId: ColumnId-10.0.1703691407556
                        Colors: []
                        Values: []
                    SortConfiguration:
                      CategoryItemsLimitConfiguration:
                        OtherCategories: INCLUDE
                      ColorItemsLimitConfiguration:
                        OtherCategories: INCLUDE
                      SmallMultiplesLimitConfiguration:
                        OtherCategories: INCLUDE
                    Tooltip:
                      FieldBasedTooltip:
                        AggregationVisibility: HIDDEN
                        TooltipFields:
                          - FieldTooltipItem:
                              FieldId: ColumnId-10.0.1703691407556
                              Visibility: VISIBLE
                        TooltipTitleType: PRIMARY_VALUE
                      SelectedTooltipType: DETAILED
                      TooltipVisibility: VISIBLE
                    Type: STACKED_AREA
                  ColumnHierarchies: []
                  Subtitle:
                    Visibility: VISIBLE
                  Title:
                    Visibility: VISIBLE
                  VisualId: FmiL0jBCZprRIlskilazGcramWPjdROkYAxzd0UE04PUmbXwtNTRhyRsimcGLkFE
      Name: dashboard02
      Permissions:
        - Actions:
            - quicksight:DescribeDashboard
            - quicksight:ListDashboardVersions
            - quicksight:UpdateDashboardPermissions
            - quicksight:QueryDashboard
            - quicksight:UpdateDashboard
            - quicksight:DeleteDashboard
            - quicksight:DescribeDashboardPermissions
            - quicksight:UpdateDashboardPublishedVersion
          Principal:
            Fn::Sub:
              - arn:aws:quicksight:${AWS::Region}:${AWS::AccountId}:user/default/${user}
              - user:
                  Ref: QuickSightUsername
    Metadata:
      aws:cdk:path: QsStack/dashboard02
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/yWKQQ7CIBAA39I7rMUaP1Af0NQHmC2ssmIhhSWmMf7dNp5mkpkjmPYEbYPvoq0L+sUTfK6CNqj+HgfMOJNQVlu/LZVtKPzwAlu7YPFTwuz2caSSara0e5+iY+EUv2pYxad46MAYODfPwqxzjcIzwfjnDx/2RnSAAAAA
    Metadata:
      aws:cdk:path: QsStack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2
Rules:
  CheckBootstrapVersion:
    Assertions:
      - Assert:
          Fn::Not:
            - Fn::Contains:
                - - "1"
                  - "2"
                  - "3"
                  - "4"
                  - "5"
                - Ref: BootstrapVersion
        AssertDescription: CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI.

