# aws cloudformation deploy --profile black-arrow-gang --region us-east-1 --template-file poc/output_dataset_spec.yml --stack-name MyQuicksightTest03
# aws cloudformation delete-stack --profile black-arrow-gang --region us-east-1 --stack-name MyQuicksightTest02
Resources:
  MyQuickSightDataSet:
    Type: AWS::QuickSight::DataSet
    Properties:
      AwsAccountId: "064855577434"  # Replace with your AWS Account ID
      DataSetId: "f66f2dea-7000-4d37-8bbb-da6b33329c34"  # Unique identifier for your dataset
      Name: "People02"  # Name of your dataset
      Permissions:
      - Actions:
        - quicksight:DeleteDataSet
        - quicksight:UpdateDataSetPermissions
        - quicksight:PutDataSetRefreshProperties
        - quicksight:CreateRefreshSchedule
        - quicksight:CancelIngestion
        - quicksight:ListRefreshSchedules
        - quicksight:UpdateRefreshSchedule
        - quicksight:PassDataSet
        - quicksight:DeleteRefreshSchedule
        - quicksight:DescribeDataSetRefreshProperties
        - quicksight:DescribeDataSet
        - quicksight:CreateIngestion
        - quicksight:DescribeRefreshSchedule
        - quicksight:ListIngestions
        - quicksight:UpdateDataSet
        - quicksight:DescribeDataSetPermissions
        - quicksight:DeleteDataSetRefreshProperties
        - quicksight:DescribeIngestion
        Principal: arn:aws:quicksight:us-east-1:064855577434:user/default/boss
      PhysicalTableMap:
        s3PhysicalTable:
          S3Source:
            DataSourceArn: "arn:aws:quicksight:us-east-1:064855577434:datasource/d7fe19c1-ff47-4b26-a860-c353a6f57ca2"  # ARN of the data source
            InputColumns:
              - Name: "ColumnId-1"
                Type: "STRING"
              - Name: "ColumnId-2"
                Type: "STRING"
              - Name: "ColumnId-3"
                Type: "STRING"
              - Name: "ColumnId-4"
                Type: "STRING"
              - Name: "ColumnId-5"
                Type: "STRING"
              - Name: "ColumnId-6"
                Type: "STRING"
              - Name: "ColumnId-7"
                Type: "STRING"
              - Name: "ColumnId-8"
                Type: "STRING"
              - Name: "ColumnId-9"
                Type: "STRING"
              - Name: "ColumnId-10"
                Type: "STRING"
              - Name: "ColumnId-11"
                Type: "STRING"
              - Name: "ColumnId-12"
                Type: "STRING"
              - Name: "ColumnId-13"
                Type: "STRING"
              - Name: "ColumnId-14"
                Type: "STRING"
              - Name: "ColumnId-15"
                Type: "STRING"
            UploadSettings:
              ContainsHeader: true
              Delimiter: ","
              Format: "CSV"
              StartFromRow: 1
              TextQualifier: "DOUBLE_QUOTE"
      LogicalTableMap:
        s3PhysicalTable:
          Alias: Group 1
          DataTransforms:
          - RenameColumnOperation:
              ColumnName: ColumnId-2
              NewColumnName: Employee Name
          - RenameColumnOperation:
              ColumnName: ColumnId-3
              NewColumnName: Employee ID
          - RenameColumnOperation:
              ColumnName: ColumnId-1
              NewColumnName: Date
          - RenameColumnOperation:
              ColumnName: ColumnId-12
              NewColumnName: Job Family
          - RenameColumnOperation:
              ColumnName: ColumnId-6
              NewColumnName: Date of Birth
          - RenameColumnOperation:
              ColumnName: ColumnId-11
              NewColumnName: Business Function
          - RenameColumnOperation:
              ColumnName: ColumnId-7
              NewColumnName: Gender
          - RenameColumnOperation:
              ColumnName: ColumnId-14
              NewColumnName: Notes
          - RenameColumnOperation:
              ColumnName: ColumnId-4
              NewColumnName: Tenure
          - RenameColumnOperation:
              ColumnName: ColumnId-13
              NewColumnName: Job Level
          - RenameColumnOperation:
              ColumnName: ColumnId-5
              NewColumnName: Monthly Compensation
          - RenameColumnOperation:
              ColumnName: ColumnId-10
              NewColumnName: Region
          - RenameColumnOperation:
              ColumnName: ColumnId-8
              NewColumnName: Education
          - RenameColumnOperation:
              ColumnName: ColumnId-9
              NewColumnName: Event Type
          - RenameColumnOperation:
              ColumnName: ColumnId-15
              NewColumnName: isUnique
          - CastColumnTypeOperation:
              ColumnName: Monthly Compensation
              NewColumnType: DECIMAL
          - CastColumnTypeOperation:
              ColumnName: Tenure
              NewColumnType: INTEGER
          - CastColumnTypeOperation:
              ColumnName: Date of Birth
              Format: yyyy-MM-dd
              NewColumnType: DATETIME
          - CastColumnTypeOperation:
              ColumnName: Date
              Format: yyyy-MM-dd
              NewColumnType: DATETIME
          - TagColumnOperation:
              ColumnName: Region
              Tags:
              - ColumnGeographicRole: STATE
          Source:
            PhysicalTableId: s3PhysicalTable
      ImportMode: "SPICE"  # Import mode (SPICE or DIRECT_QUERY)
      DataSetUsageConfiguration:
        DisableUseAsDirectQuerySource: false
        DisableUseAsImportedSource: false
