# Common Parameters
Country:
  Type: String
  Default: es
  AllowedValues:
    - es
    - de
    - pt
    - nl
    - ar
    - mc
    - mx
    - us
  Description: Name of the country for the tag
Project:
  Type: String
  Default: test
  Description: Name of the project for the tag

